emb_dims:
    - 16
    - 20
    - 24 
    - 32
DATA_LOC: './../../GeneratedData'
AD_model_data_subdir: 'AD_model_data'
train_epochs : 250
learning_rate : 0.001
batch_size : 256
error_tol : 0.005
model_save_dir: './ad_model_saved'
perc_threshold :
 - 1
 - 2
 - 3
 - 4 
 - 5 
 - 10
